export const items = [
  // ===== MOBILES (1–25) =====
  { id: 1, category: 'mobiles', title: "Apple iPhone 14", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Apple iPhone 14 (128 GB)', price: '89999' },
  { id: 2, category: 'mobiles', title: "Apple iPhone 13", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Apple iPhone 13 (128 GB)', price: '69999' },
  { id: 3, category: 'mobiles', title: "Apple iPhone 11", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Apple iPhone 11 (64 GB)', price: '59999' },
  { id: 4, category: 'mobiles', title: "Samsung Galaxy S23", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Samsung Galaxy S23 5G', price: '74999' },
  { id: 5, category: 'mobiles', title: "Samsung Galaxy A54", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Samsung Galaxy A54 5G', price: '34999' },
  { id: 6, category: 'mobiles', title: "OnePlus 11R", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'OnePlus 11R 5G', price: '39999' },
  { id: 7, category: 'mobiles', title: "OnePlus Nord CE 3", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'OnePlus Nord CE 3', price: '29999' },
  { id: 8, category: 'mobiles', title: "Redmi Note 12 Pro", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Redmi Note 12 Pro 5G', price: '24999' },
  { id: 9, category: 'mobiles', title: "Redmi 13C", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Redmi 13C Budget Phone', price: '10999' },
  { id: 10, category: 'mobiles', title: "Realme GT Neo 3", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Realme GT Neo 3 5G', price: '29999' },
  { id: 11, category: 'mobiles', title: "Realme Narzo 60", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Realme Narzo 60', price: '17999' },
  { id: 12, category: 'mobiles', title: "Vivo V29", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Vivo V29 5G', price: '32999' },
  { id: 13, category: 'mobiles', title: "Vivo Y20", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Vivo Y20 Budget', price: '11999' },
  { id: 14, category: 'mobiles', title: "Oppo Reno 10", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Oppo Reno 10 Pro', price: '36999' },
  { id: 15, category: 'mobiles', title: "Oppo A78", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Oppo A78 5G', price: '18999' },
  { id: 16, category: 'mobiles', title: "iQOO Neo 7", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'iQOO Neo 7 Gaming', price: '30999' },
  { id: 17, category: 'mobiles', title: "iQOO Z7", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'iQOO Z7 5G', price: '21999' },
  { id: 18, category: 'mobiles', title: "Motorola Edge 40", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Motorola Edge 40', price: '29999' },
  { id: 19, category: 'mobiles', title: "Motorola G54", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Motorola G54 5G', price: '15999' },
  { id: 20, category: 'mobiles', title: "Infinix Zero 5G", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Infinix Zero 5G', price: '14999' },
  { id: 21, category: 'mobiles', title: "Tecno Spark 10", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Tecno Spark 10', price: '9999' },
  { id: 22, category: 'mobiles', title: "Nokia G42", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Nokia G42 5G', price: '13999' },
  { id: 23, category: 'mobiles', title: "Samsung Galaxy M14", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Samsung Galaxy M14', price: '12999' },
  { id: 24, category: 'mobiles', title: "Samsung Galaxy F54", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Samsung Galaxy F54', price: '25999' },
  { id: 25, category: 'mobiles', title: "Google Pixel 7a", imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg', amazonLink: '#', description: 'Google Pixel 7a', price: '43999' },

  // ===== LAPTOPS (26–45) =====
  { id: 26, category: 'laptops', title: "MacBook Air M1", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Apple MacBook Air M1', price: '89999' },
  { id: 27, category: 'laptops', title: "MacBook Pro M2", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Apple MacBook Pro M2', price: '129999' },
  { id: 28, category: 'laptops', title: "Dell Inspiron 15", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Dell Inspiron i5', price: '57999' },
  { id: 29, category: 'laptops', title: "HP Pavilion 14", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'HP Pavilion Ryzen 5', price: '64999' },
  { id: 30, category: 'laptops', title: "Lenovo IdeaPad Slim 5", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Lenovo Slim 5 i5', price: '59999' },
  { id: 31, category: 'laptops', title: "Asus Vivobook OLED", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Asus Vivobook OLED', price: '54999' },
  { id: 32, category: 'laptops', title: "Acer Aspire 7", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Acer Aspire 7 Gaming', price: '56999' },
  { id: 33, category: 'laptops', title: "MSI GF63", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'MSI GF63 Gaming', price: '62999' },
  { id: 34, category: 'laptops', title: "Asus TUF Gaming", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Asus TUF Gaming F15', price: '74999' },
  { id: 35, category: 'laptops', title: "HP Victus", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'HP Victus Gaming', price: '78999' },
  { id: 36, category: 'laptops', title: "Lenovo Legion 5", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Lenovo Legion 5', price: '89999' },
  { id: 37, category: 'laptops', title: "Dell XPS 13", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Dell XPS 13 Premium', price: '129999' },
  { id: 38, category: 'laptops', title: "Samsung Galaxy Book", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Samsung Galaxy Book', price: '69999' },
  { id: 39, category: 'laptops', title: "Microsoft Surface Laptop", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'Surface Laptop 5', price: '109999' },
  { id: 40, category: 'laptops', title: "LG Gram", imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg', amazonLink: '#', description: 'LG Gram Ultra Light', price: '99999' },

  // ===== TABLETS (41–55) =====
  { id: 41, category: 'tablets', title: "iPad 10th Gen", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Apple iPad 10th Gen', price: '44999' },
  { id: 42, category: 'tablets', title: "iPad Air", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Apple iPad Air', price: '59999' },
  { id: 43, category: 'tablets', title: "Samsung Tab S9", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Samsung Galaxy Tab S9', price: '69999' },
  { id: 44, category: 'tablets', title: "Samsung Tab A8", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Samsung Tab A8', price: '24999' },
  { id: 45, category: 'tablets', title: "Xiaomi Pad 6", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Xiaomi Pad 6', price: '29999' },
  { id: 46, category: 'tablets', title: "Lenovo Tab P12", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Lenovo Tab P12', price: '24999' },
  { id: 47, category: 'tablets', title: "Realme Pad", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Realme Pad', price: '15999' },
  { id: 48, category: 'tablets', title: "Nokia T21", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Nokia T21 Tablet', price: '17999' },
  { id: 49, category: 'tablets', title: "Honor Pad X9", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Honor Pad X9', price: '19999' },
  { id: 50, category: 'tablets', title: "Microsoft Surface Go", imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg', amazonLink: '#', description: 'Surface Go', price: '49999' },

  // ===== ACCESSORIES (51–70) =====
  { id: 51, category: 'accessories', title: "Apple AirPods Pro", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Noise Cancelling', price: '24999' },
  { id: 52, category: 'accessories', title: "Apple AirPods 3", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'AirPods 3rd Gen', price: '18999' },
  { id: 53, category: 'accessories', title: "Samsung Galaxy Buds 2", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Galaxy Buds 2', price: '9999' },
  { id: 54, category: 'accessories', title: "Sony WH-1000XM5", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Sony Headphones', price: '34999' },
  { id: 55, category: 'accessories', title: "Boat Rockerz 550", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Boat Headphones', price: '1999' },
  { id: 56, category: 'accessories', title: "Logitech Wireless Mouse", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Wireless Mouse', price: '1499' },
  { id: 57, category: 'accessories', title: "Logitech Keyboard", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Mechanical Keyboard', price: '4999' },
  { id: 58, category: 'accessories', title: "Apple Magic Mouse", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Apple Mouse', price: '7999' },
  { id: 59, category: 'accessories', title: "USB-C Hub", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Multiport Adapter', price: '2999' },
  { id: 60, category: 'accessories', title: "External SSD 1TB", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: '1TB SSD Storage', price: '8999' },
  { id: 61, category: 'accessories', title: "Power Bank 20000mAh", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Fast Charging', price: '2499' },
  { id: 62, category: 'accessories', title: "Smart Watch", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Fitness Watch', price: '3999' },
  { id: 63, category: 'accessories', title: "Bluetooth Speaker", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Portable Speaker', price: '2999' },
  { id: 64, category: 'accessories', title: "Webcam HD", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'HD Webcam', price: '1999' },
  { id: 65, category: 'accessories', title: "Laptop Stand", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Adjustable Stand', price: '1499' },
  { id: 66, category: 'accessories', title: "Wireless Charger", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Fast Wireless Charger', price: '1999' },
  { id: 67, category: 'accessories', title: "Gaming Mouse", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'RGB Gaming Mouse', price: '2499' },
  { id: 68, category: 'accessories', title: "Laptop Backpack", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Waterproof Bag', price: '1999' },
  { id: 69, category: 'accessories', title: "Screen Protector", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Tempered Glass', price: '499' },
  { id: 70, category: 'accessories', title: "Phone Case", imgSrc: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg', amazonLink: '#', description: 'Shockproof Case', price: '799' }
];
